_wandb:
    value:
        cli_version: 0.23.1
        e:
            pxxd7loqfi83ulildb743mzs8jalm4vu:
                args:
                    - --lmbd
                    - "0.4"
                codePath: run_Q_model.py
                codePathLocal: run_Q_model.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "107306024960"
                        used: "63429935104"
                email: marvin.mathony@gmail.com
                executable: /ictstr01/home/hcai/marvin.mathony/tools/apps/mamba/envs/RNNproject/bin/python
                git:
                    commit: 8e18d0660fd46839b703731eecfd6f79c4e7cc69
                    remote: https://marvinmathony:@github.com/marvinmathony/ClusterRNNIndDiffs.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-0c2c56c4-9dfb-b684-5d3f-56ade29061a0
                host: gpusrv64.scidom.de
                memory:
                    total: "540197658624"
                os: Linux-5.14.0-570.25.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /ictstr01/home/hcai/marvin.mathony/RNNsandUncertainty/run_Q_model.py
                python: CPython 3.9.19
                root: /ictstr01/home/hcai/marvin.mathony/RNNsandUncertainty
                slurm:
                    cluster_name: algoritam
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: aih
                    job_cpus_per_node: "4"
                    job_end_time: "1764902671"
                    job_gid: "20309"
                    job_gpus: "0"
                    job_id: "32804414"
                    job_name: interactive
                    job_nodelist: gpusrv64
                    job_num_nodes: "1"
                    job_partition: gpu_p
                    job_qos: gpu_normal
                    job_start_time: "1764859471"
                    job_uid: "1000263"
                    job_user: marvin.mathony
                    jobid: "32804414"
                    launch_node_ipaddr: 10.233.0.251
                    localid: "0"
                    mem_per_node: "32768"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpusrv64
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "60843"
                    pty_win_col: "262"
                    pty_win_row: "15"
                    srun_comm_host: 10.233.0.251
                    srun_comm_port: "60463"
                    step_id: "4294967290"
                    step_launcher_port: "60463"
                    step_nodelist: gpusrv64
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /ictstr01/home/hcai/marvin.mathony/RNNsandUncertainty
                    submit_host: hpc-submit01.scidom.de
                    task_pid: "1925389"
                    tasks_per_node: "1"
                    topology_addr: gpusrv64
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2025-12-04T15:49:47.782691Z"
                writerId: pxxd7loqfi83ulildb743mzs8jalm4vu
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
            "3":
                - 16
                - 61
            "4": 3.9.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
lmbd:
    value: 0.4
